name: DiddyMC
version: '1.0'
main: me.houdert6.paper.DiddyMC
bootstrapper: me.houdert6.paper.bootstrap.DiddyMCBootstrap
api-version: '1.19'
description: 'Brainrot Minecraft plugin.'
authors: [houdert6]
contributors: [Unprankable]
website: 'https://discord.gg/u6AVRt7Bgm'
dependencies:
  server:
    DiscordSRV:
      load: BEFORE
      join-classpath: true
      required: false
permissions:
  diddymc.rizzme:
    description: 'Allows people to use /rizzme'
    default: true
  diddymc.oil:
    description: 'Allows people to use /oil'
    default: true
  diddymc.diddle:
    description: 'Allows people to use /diddle'
    default: true
  diddymc.getaura:
    description: 'Allows people to use /getaura'
    default: true